Add manage of highlight that render as chp backgroundColor
tbluemel/rtf.js pull request #79
Opened 2021-03-22 07:18 UTC by msturari

Add parsing of \highlight parameter that is rendered as chp backgroundColor

2021-03-22 14:38 UTC, zoehneto commented
Thank you for your contribution. 
Please add a test document showing the feature in action (see https://github.com/tbluemel/rtf.js#tests for how to generate a test case). You also have to run `npm run build` and commit the new version of the js bundles so the build passes (unfortunately travis ci doesn't post the build results in the PR anymore, see https://travis-ci.org/github/tbluemel/rtf.js/builds/763900576).

2021-03-22 16:48 UTC, msturari commented
Hi, I have added bundle files and a test document.

2021-03-22 17:41 UTC, zoehneto requested changes
For some reason the generated source maps don't match what's generated on travis ci (also not what is generated when I run `npm run build` locally). You may want to try reinstalling the dependencies with `npm ci` so you get the correct versions.

2021-03-22 17:41 UTC, zoehneto commented on test/rtf-test-files/colors/expected-metadata.json
> +{
This doesn't match the meta data in the rtf file, please regenerate the test case

2021-03-22 17:41 UTC, zoehneto commented on test/rtf-test-files/colors/expected.html
> +<div style="min-height: 8pt; text-align: left;">
I assume your editor formatted this file. That breaks the test though. When you regenerate the test case this should be fixed automatically.

2021-03-23 14:14 UTC, zoehneto approved these changes
The source maps were still incorrect, I've regenerated them and pushed that change. Will merge now.

2021-03-23 14:18 UTC, merged